### ISSUE TITLE
Minor changes in prepro and train_model_autoencoder.py for LSTM

### ISSUE THREAD

**Issue by NikoHobel** [saraghsm/sound-of-failure#11]
Hi Wriju,

I have finished the module for LSTM-AE now. It is simpler than the conv AEs taking only `input_shape` and `num_nodes` as args. The functions in train_model_autoencoder.py can be directly applied to or extended for this model. I would include a code block for `model_name=='lstmAE'` in `load_new_model()` and set the conv specific args to `None` by default.

Also I in the prepro functions I want to include a new arg `as_image=True` to control if the output shape gets a channel dimension or not.

No existing code will run differently with the changes I have in mind. 
Do you have any objections or comment? 
Otherwise I will go ahead either later today or tomorrow.

**Comment by wrijupan** [comment]
Hi Niklas,

Good to know that the LSTMs are almost done! Please go ahead with the changes if you ensure nothing will break when trying to re-run.

**Comment by NikoHobel** [comment]
Implemented and talked through, I believe ;)
