### ISSUE TITLE
Sharing trained models

### ISSUE THREAD

**Issue by NikoHobel** [saraghsm/sound-of-failure#13]
Hi Wriju,

could you push good trained models to the github? 
I suggest you store them under a non-standard run ID using `naming.copy_run(run_id, new_run_id)`. 
In this function you can specify new run ID by hand, for example "VAE_6dB_valve_id_00_final". 
The model, the scaler and the config file would have to be pushed.

I am not ready to share a "final" model, because I want to try out your recent spectrogram settings. 
That is not strictly necessary, but it would be nice to evaluate all different models on the same data.

Thanks

**Comment by wrijupan** [comment]
Shared the VAE. Probably will also share the AE final models. But have to adapt the notebook for the AE. The notebook for AE is lacking behind the last few commits. 
Closing this issue.
