### ISSUE TITLE
Bug fix: src/01_data_processing/spectrogram.py

### ISSUE THREAD

**Issue by saraghsm** [saraghsm/sound-of-failure#4]
This line: 

`make_mel_dirs(base_dir, db, machine_type, machine_id)`

should be added [here](https://github.com/saraghsm/sound-of-failure/blob/ec7755d3e386068728be98467aebf2780238b5fe/src/01_data_processing/spectrogram.py#L123). (If the directory exists, it won't be overwritten. But if it doesn't, then we need it in order to get it and then populate it with mel spectrograms.)

and then from line [125](https://github.com/saraghsm/sound-of-failure/blob/ec7755d3e386068728be98467aebf2780238b5fe/src/01_data_processing/spectrogram.py#L125)  to line [130](https://github.com/saraghsm/sound-of-failure/blob/ec7755d3e386068728be98467aebf2780238b5fe/src/01_data_processing/spectrogram.py#L130) should go inside the `get_mel_dirs` function. (So basically inside the `get_mel_dirs` should check if the directory exists, then get the directory, and if it does not exist, then tell the user to first run ` make_mel_dirs` first.)

**Comment by NikoHobel** [comment]
That was my original thinking. 

But then, when I had this line in the script, it through an error message for directory not existing.
I believe it was, because because the newly created directory didn't sync to the drive quickly enough.

Hence I decided to create the directories separately and added the function get_mel_dirs for readability.

Could go with your suggestion and write a loop that checks if directory exists until it does - before proceeding to spectrogram creation. 
Could hurt readability.

**Comment by saraghsm** [comment]
I see! 

Having `make_mel_dirs` and `get_mel_dirs` separately is of course a good practice, I just wanted to call the `make_mel_dirs` inside the `make_mels`, rather than accounting the user to call it in advance. But now I understand the reason behind it.

GitHub has some pre-define labels for issues, bug was the closest one. I refer to anything that would be better to get fixed in the code as "bug", only for the lack of label, but you can define a dedicated label for it and add it here! Also, bug is not necessarily something that makes the code to crash or give wrong answer. If the code gives the responsibility to the user to remember to do something while that thing could have been done automatically, then there is a potential for the code to not function :) Anyways, I was not really picky about whether or not it's called bug ;)

**Comment by wrijupan** [comment]
On a related note, `    wav_lists = [get_normal_wav_files(raw_data_dir, db, machine_type, machine_id),` `                 get_abnormal_wav_files(raw_data_dir, db, machine_type, machine_id)]`. These two lines inside the `make_mels` function does not check whether the `raw_data_dir` is a valid path, does it?

**Comment by NikoHobel** [comment]
No, they don't. 

I believe lists will be empty if path is not valid. But I'm not sure.
Should I add a functionality checking this?

**Comment by wrijupan** [comment]
Hi Niklas,
It would be nice to add some kind of check. I was briefly checking that even if I give a wrong path to the raw dir, the program runs and in the end produces spectrograms that are blank (black colour with no lines).

**Comment by NikoHobel** [comment]
Made changes to the respective scripts. 
Closing this issue now.
