### ISSUE TITLE
Discussion : creating config files and storing them

### ISSUE THREAD

**Issue by wrijupan** [saraghsm/sound-of-failure#5]
1. Currently the scripts for creating config files are stored inside [`src/00_utils`](https://github.com/saraghsm/sound-of-failure/tree/main/src/00_utils). Is this a good place to save such scripts? Does the structure of these scripts need modification?

2. There are two steps currently: creating config files and reading config files. In the creation step, some of the parameters are read via the cmd line (see for an [example).](https://github.com/saraghsm/sound-of-failure/blob/main/notebooks/WB_20210318_ConvAE_training_demo.ipynb) The cmd-line parameters are for the user to play with. How many parameters can we pass through the command line? (there are too many parameters and not all of them should be passed via cmd-line)

3. Config files are stored inside [`sound-of-failure/conf`.](https://github.com/saraghsm/sound-of-failure/tree/main/conf). Is the current structure of the config file okay?

**Comment by NikoHobel** [comment]
Hi Wriju,

thanks for this!

1. Good place for those scripts. Excellently readable! Reading them, I wonder if it would be useful to have three config files for base, preprocessing and modelling, respectively. The third one would be very specific to the model of choice. But I suggest we wait and see, if the preprocessing steps are really shared between experiments.

2. Good choice of parameters to be parsed in the command line. It's more or less in line with my view on what's generic and what's very model specific.

3. Files are looking good. Only thing I would suggest is to include default values for num_nodes, num_kernel and num_strides in the config file.

**Comment by saraghsm** [comment]
Thanks Wriju for the scripts!

1. Fine by me as well! I would just change the names to e.g.  `create_conf_base.py` or `make_conf_base.py` 
2. This I can not say from now, I think we will see it in work. A `--help`or `-h` would be very useful and is a common practice to list all the command line parameters (or is it already there?!)
3. All looks good to me :) I just was wondering if [db](https://github.com/saraghsm/sound-of-failure/blob/9be69576f2a048235a79e10f38004973e2d48acd/conf/conf_convAE.ini#L11) would be a confusing name, but that's not so important.

**Comment by wrijupan** [comment]
Hi Sara, Niklas,

Made some minor changes in the scripts for creating config files to address your concerns: renaming, adding the strides, num_kernels etc for Conv Autoencoder.

Niklas, yes these are some basic config files. We can make them more sophisticated and maybe even disentangle base, preprocessing, modelling configs in future. Let's keep discussing.

Sara, the -h flag is there by default for cmd-line parameters. I have added an example in the updated notebook.

If for now, you have no additional comments I will close the issue.

**Comment by wrijupan** [comment]
Just added a small change to the [script](https://github.com/saraghsm/sound-of-failure/blob/main/src/00_utils/make_conf_convAE.py). 

Now there is an additional cmd-line parameter AE or VAE. Which creates a config file accordingly (i.e. whether the params are for a AE or VAE). Since both AE and VAE belong to the same class of model the script to create such config files can be same. Just the name of the config file and the parameters inside it can be different.
