### ISSUE TITLE
Discussion: Name convention and structure of models

### ISSUE THREAD

**Issue by saraghsm** [saraghsm/sound-of-failure#8]
My suggestion for the naming convention for the models :

`<model_name>_<noise_ratio>_<machine_name>_<machin_id>`

The order mirrors the structure of our data directory (i.e. `.../sound-of-failure/data/mel_spectrograms/6dB/valve/id_00/...` ), otherwise I am personally not a fan of the noise_ratio being first. But again, as a physicist I love symmetry, so I suggest to mirror the data folder structure!!!  

- <model_name> = {convae, vae, lstm, lstmae, convlstmae, isoforest, ...} ---> i.e. abbreviation of the model names, and we'll add in the README file what is the meaning of each abbreviation. We should decide if we want capital or small letters or combination, and be consistent _every where_ throughout the GitHub repo,  every where! :)
- <noise_ratio> = {6dB, 0dB, min6dB, all} ---> 'all' is for the case that we train on all the noise ratios together
- <machine_name> = {valve, fan, pump, slider}
- <machin_id> = {id00, id02, id04, id06, all} ---> 'all': as above

Then we will have these files:

- `conf/conf_<model_name>_<noise_ratio>_<machine_name>_<machin_id>.ini` ---> for the configuration file that keeps the hyperparameters of that model which is trained / going to be trained for that specific machine, id, etc.
- `model/<model_name>_<noise_ratio>_<machine_name>_<machin_id>.hdf5` ---> for the model that we save after training

and anywhere else that anything specific for these combination of model, machine, id, ... is needed to be saved (for example maybe in output folder ?!) the similar name convention can be used.

To avoid git conflicts, we can add to .gitignor the lines `conf/conf_*.ini` and `model/*.hdf5`, and then we manually save the _**best**_  model and its relevant config file with names like `conf/final_conf_<...>.ini` and `model/final_<...>.hdf5` so that only these best and supposedly final versions will be pushed and kept in GitHub, and they are being freezed and not overwritten by any of the scripts. 

Note that we might come up with even a better version of our already best model, but that should be again saved under the name with format final_<...>, i.e. please avoid names like final01_<...>, final_2_<...>, final_final_<...>, with the version control we can always retrieve older versions, no need to protect them but these sort of names.

**Comment by saraghsm** [comment]
already apologising for my mis-use of labels! You can totally change them! :)

**Comment by NikoHobel** [comment]
Hi, generally agree with the naming convention. For local usage (running different models that would have same default name) I suggest a solution in a separate issue. I also suggest using a name as a consistent reference throughout the code - as some sort of session id. Happy to hear your opinion over there.

**Comment by NikoHobel** [comment]
Ok, all in one place then.

**Comment by NikoHobel** [comment]
Hi guys,

this is my suggestion to implement our naming convention. 

I think the following script should be called when creating new config files so they can be stored according to the naming convention. This means the respective scripts (`make_conf_base.py` and the other one) need to take `model_name`, `db`, `machine_type` and `machine_id`. The script just makes sure the name is not taken already.

```
def get_scaler_path(name_string):
  return os.path.join('models', name_string + '_scaler.gz')

def get_conf_path(name_string):
  return os.path.join('conf', 'conf_' + name_string + '.ini')

def get_conf_base_path(name_string):
  return os.path.join('conf', 'conf_base_' + name_string + '.ini')

def get_model_path(name_string):
  return os.path.join('models', name_string + '.hdf5')


def get_new_name_string(model_name, db, machine_type, machine_id):
  name_string = model_name +'_' + db +'_' + machine_type +'_' + machine_id

  # Check if new_name_string is new
  count = 1
  new_name_string = name_string
  
  while os.path.exists(get_scaler_path(new_name_string)):
    new_name_string = name_string + '_' + str(count)
    count += 1

  while os.path.exists(get_model_path(new_name_string)):
    new_name_string = name_string + '_' + str(count)
    count += 1
  
  while os.path.exists(get_conf_base_path(new_name_string)) or os.path.exists(get_conf_path(new_name_string)):
    new_name_string = name_string + '_' + str(count)
    count += 1

  return new_name_string
```

I suggest we use `name_string` as a consistent reference throughout the code. It must be initially chosen. 

So instead of
```
base_conf = train.read_config('/gdrive/MyDrive/sound-of-failure/conf/conf_base.ini')
param_conf = train.read_config('/gdrive/MyDrive/sound-of-failure/conf/conf_VAE.ini')
```
 we will use sth like
```
base_conf = train.read_config(name_string)
param_conf = train.read_config(name_string)
```

Do you think this could be a useful structure?

**Comment by saraghsm** [comment]
1. > def get_conf_base_path(name_string):
  return os.path.join('conf', 'conf_base_' + name_string + '.ini')

Do we really want to have a conf_base file for every model+dB+machine+id ?

2. Let me know if I understood correctly, we take take `model_name`, `db`, `machine_type` and `machine_id` and make a `name_string` from them (so `name_string = <model_name>_db_<machine_type>_ <machine_id>`). Then why we want to protect it by checking if the name is not taken before? Every time that I want to train my model with different parameters I should be able to make a new config file for it. If the make_conf script does not allow me to overwrite, then I can only make a config file for the first time and the rest of the times I have to edit the existing config file manually. If that's your suggestion, then we can think about it. But I would like to avoid any editing by hand inside the conf files.

**Comment by NikoHobel** [comment]
1.
If `conf_base.ini` NEVER EVER changes, there is no need. 

2.
Currently there are parameters in the config files that can only be modified manually. 
The specifics of layers, for example, are at some default values. 
They are not controlled through the command line.
I find that preferable to overloading the command line. 

So to train a model with parameters different from default you would manually modify the config file before reading it.
If you think what you have done before should be kept, you would create new config files (taking a new name) and start modifying these.

**Comment by saraghsm** [comment]
One more question: 

> def get_scaler_path(name_string):
  return os.path.join('models', name_string + '_scaler.gz')

Do we need to save one scaler per model, or one scaler per dB+machine_type+machine_id is enough? Is it because the type of scaler that we used is defined in the model's config file? How about `<scaler_type>_<dB>_<machine_type>_<machine_id>`, if different models can benefit from it?

**Comment by NikoHobel** [comment]
We may want to try different scalers. A scaler is two numbers, more or less, it does not take a lot of space.

My main goal here is to have some sort of log of what I'm doing. Of what has been used together.
So I would like to store the scaler with the rest. It will also be different in case a different value of `n_mels` was chosen. Or `hop-length`. So more likely than not the scaler will be different between experiments.

**Comment by saraghsm** [comment]
I see. Then as long as that if I change, say, `n_mels` or `hop-length` _by hand_ inside the `conf_<model_name>_<db>_<machine_type>_ <machine_id>`, the mel_spectograms and the scaler files are guaranteed to be reproduced and overwritten, it all seem ok to me. Thanks!

**Comment by NikoHobel** [comment]
Would include an overwrite argument to the respective functions, so you can control if you want to overwrite or not. 
It should prompt you saying 
```

'this_scaler.gz' already exists and was loaded. 
Pleasew run fit_scaler(..., overwrite=True) to fit a new scaler.
```

To be discussed.

**Comment by wrijupan** [comment]
Hi Niklas,

We already talked via phone but let me summarize my comments here again 👍 

1) In principle the naming convention `model_name +'_' + db +'_' + machine_type +'_' + machine_id` is fine. 

2) In the script above the counter forces 1,2,3 etc if the file already exists. Since we are past the stage of experimentation and playing around with parameters, this is not strictly necessary. For private experimentation, one can choose to do that, however. So it should be up to the user whether they want to append the counter at the end of the name or not. In github while deployment we will only follow the naming convention `model_name +'_' + db +'_' + machine_type +'_' + machine_id` without the counter appended.

3) Best is to demonstrate the use case through your notebook. Maybe once you have the LSTM notebook ready it will be easier to see the new functionalities.

**Comment by saraghsm** [comment]
Just a reminder that at the moment config files are ignored by git.

Let's move on, so far it's been a solid plan, and we'll see while working if any changes are required.

**Comment by NikoHobel** [comment]
Implemented and talked through, I believe ;)
